### GET /Funcionarios
GET http://localhost:5078/Funcionarios

### GET /Funcionarios/{id}
GET http://localhost:5078/Funcionarios/5

### POST /Funcionarios
POST http://localhost:5078/Funcionarios
Content-Type: application/json

{
  "nome": "Arnaldo",
  "cpf": "00011122233",
  "cargo": "analista",
  "dataContratacao": "2024-11-06T00:00:00",
  "salario": 1200,
  "endereco": "Curitiba",
  "telefone": "222222"
}


### PUT /Funcionarios
PUT http://localhost:5078/Funcionarios/5
Content-Type: application/json

{
  "nome": "Junior",
  "cpf": "00011122244",
  "cargo": "eng",
  "dataContratacao": "2024-11-06T00:00:00",
  "salario": 1200,
  "endereco": "Curitiba",
  "telefone": "222222"
}

### DELETE /Funcionarios/{id}
DELETE http://localhost:5078/Funcionarios/4